### ISSUE TITLE
ModuleNotFoundError: No module named 'pycose.keys'

### ISSUE THREAD

**Issue by Paul2708** [eu-digital-identity-wallet/eudi-srv-web-issuing-eudiw-py#45]
Hey there,

I followed the installation guide using Python 3.9.2 on Windows.
However, after completing the installation, the command `flask --app app run --debug` raises the following error:

```
(.venv) PS C:\Workspace\cm\EUDI-Wallet\eudi-srv-web-issuing-eudiw-py> flask --app app run --debug
Usage: flask run [OPTIONS]
Try 'flask run --help' for help.

Error: While importing 'app', an ImportError was raised:

Traceback (most recent call last):
  File "c:\workspace\cm\eudi-wallet\eudi-srv-web-issuing-eudiw-py\.venv\lib\site-packages\flask\cli.py", line 219, in locate_app
    __import__(module_name)
  File "C:\Workspace\cm\EUDI-Wallet\eudi-srv-web-issuing-eudiw-py\app\__init__.py", line 41, in <module>
    from pycose.keys import EC2Key
ModuleNotFoundError: No module named 'pycose.keys'
```

Did I miss something, or is the current state not working properly?

Thanks in advance.

Greetings,
Paul

**Installation Details:**

<details><summary>Installation Log</summary>

```
PS C:\Workspace\cm\EUDI-Wallet\eudi-srv-web-issuing-eudiw-py> python -m venv .venv
PS C:\Workspace\cm\EUDI-Wallet\eudi-srv-web-issuing-eudiw-py> . .venv\Scripts\Activate
(.venv) PS C:\Workspace\cm\EUDI-Wallet\eudi-srv-web-issuing-eudiw-py> python -m pip install --upgrade pip
Collecting pip
  Using cached pip-24.2-py3-none-any.whl (1.8 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 20.2.3
    Uninstalling pip-20.2.3:
      Successfully uninstalled pip-20.2.3
Successfully installed pip-24.2
(.venv) PS C:\Workspace\cm\EUDI-Wallet\eudi-srv-web-issuing-eudiw-py> pip install -r app/requirements.txt
Collecting git+https://github.com/eu-digital-identity-wallet/pyMDOC-CBOR.git (from -r app/requirements.txt (line 25))
  Cloning https://github.com/eu-digital-identity-wallet/pyMDOC-CBOR.git to c:\users\paul\appdata\local\temp\pip-req-build-8nsax8m2
  Running command git clone --filter=blob:none --quiet https://github.com/eu-digital-identity-wallet/pyMDOC-CBOR.git 'C:\Users\Paul\AppData\Local\Temp\pip-req-build-8nsax8m2'
  Resolved https://github.com/eu-digital-identity-wallet/pyMDOC-CBOR.git to commit b8f3bfe93caebd03260cfa9e9fded221cf987fef
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting git+https://github.com/eu-digital-identity-wallet/idpy-oidc.git (from -r app/requirements.txt (line 26))
  Cloning https://github.com/eu-digital-identity-wallet/idpy-oidc.git to c:\users\paul\appdata\local\temp\pip-req-build-tjbshcrz
  Running command git clone --filter=blob:none --quiet https://github.com/eu-digital-identity-wallet/idpy-oidc.git 'C:\Users\Paul\AppData\Local\Temp\pip-req-build-tjbshcrz'
  Resolved https://github.com/eu-digital-identity-wallet/idpy-oidc.git to commit bad066ff7e0f7e2e00a19577f5dde5f7417fdcb7
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting git+https://github.com/eu-digital-identity-wallet/openid4v.git (from -r app/requirements.txt (line 27))
  Cloning https://github.com/eu-digital-identity-wallet/openid4v.git to c:\users\paul\appdata\local\temp\pip-req-build-00wiqehr
  Running command git clone --filter=blob:none --quiet https://github.com/eu-digital-identity-wallet/openid4v.git 'C:\Users\Paul\AppData\Local\Temp\pip-req-build-00wiqehr'
  Resolved https://github.com/eu-digital-identity-wallet/openid4v.git to commit 5ffeccccf1e4009cc1ba303b900694babc52b9cd
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting git+https://github.com/openwallet-foundation-labs/sd-jwt-python.git@9181a0a4514b7de2cc30a84d320b509e9fc5cb59 (from -r app/requirements.txt (line 28))
  Cloning https://github.com/openwallet-foundation-labs/sd-jwt-python.git (to revision 9181a0a4514b7de2cc30a84d320b509e9fc5cb59) to c:\users\paul\appdata\local\temp\pip-req-build-2uz5uzzj
  Running command git clone --filter=blob:none --quiet https://github.com/openwallet-foundation-labs/sd-jwt-python.git 'C:\Users\Paul\AppData\Local\Temp\pip-req-build-2uz5uzzj'
  Running command git rev-parse -q --verify 'sha^9181a0a4514b7de2cc30a84d320b509e9fc5cb59'
  Running command git fetch -q https://github.com/openwallet-foundation-labs/sd-jwt-python.git 9181a0a4514b7de2cc30a84d320b509e9fc5cb59
  starting fsmonitor-daemon in 'C:/Users/Paul/AppData/Local/Temp/pip-req-build-2uz5uzzj'
  Running command git checkout -q 9181a0a4514b7de2cc30a84d320b509e9fc5cb59
  Resolved https://github.com/openwallet-foundation-labs/sd-jwt-python.git to commit 9181a0a4514b7de2cc30a84d320b509e9fc5cb59
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting git+https://github.com/rohe/fedservice.git (from -r app/requirements.txt (line 29))
  Cloning https://github.com/rohe/fedservice.git to c:\users\paul\appdata\local\temp\pip-req-build-goimzp2_
  Running command git clone --filter=blob:none --quiet https://github.com/rohe/fedservice.git 'C:\Users\Paul\AppData\Local\Temp\pip-req-build-goimzp2_'
  Resolved https://github.com/rohe/fedservice.git to commit a45cac78643867b3f59dfd24fa93d25e5bc99dc5
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting git+https://github.com/rohe/idpy-sdjwt.git (from -r app/requirements.txt (line 30))
  Cloning https://github.com/rohe/idpy-sdjwt.git to c:\users\paul\appdata\local\temp\pip-req-build-59c69q5s
  Running command git clone --filter=blob:none --quiet https://github.com/rohe/idpy-sdjwt.git 'C:\Users\Paul\AppData\Local\Temp\pip-req-build-59c69q5s'
  Resolved https://github.com/rohe/idpy-sdjwt.git to commit de1715ef89c7f3db5daf3cdc53fec26d6ade03d9
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting Flask-Cors==4.0.0 (from -r app/requirements.txt (line 1))
  Using cached Flask_Cors-4.0.0-py2.py3-none-any.whl.metadata (5.4 kB)
Collecting requests==2.31.0 (from -r app/requirements.txt (line 2))
  Using cached requests-2.31.0-py3-none-any.whl.metadata (4.6 kB)
Collecting cbor2==5.4.6 (from -r app/requirements.txt (line 3))
  Downloading cbor2-5.4.6-cp39-cp39-win_amd64.whl.metadata (5.8 kB)
Collecting pytz==2023.4 (from -r app/requirements.txt (line 4))
  Using cached pytz-2023.4-py2.py3-none-any.whl.metadata (22 kB)
Collecting flask==2.3.3 (from -r app/requirements.txt (line 5))
  Using cached flask-2.3.3-py3-none-any.whl.metadata (3.6 kB)
Collecting pyignite==0.6.1 (from -r app/requirements.txt (line 6))
  Downloading pyignite-0.6.1-cp39-cp39-win_amd64.whl.metadata (5.3 kB)
Collecting tinyec==0.4.0 (from -r app/requirements.txt (line 7))
  Using cached tinyec-0.4.0.tar.gz (24 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pycryptodome==3.20.0 (from -r app/requirements.txt (line 8))
  Using cached pycryptodome-3.20.0-cp35-abi3-win_amd64.whl.metadata (3.4 kB)
Collecting config==0.5.1 (from -r app/requirements.txt (line 9))
  Using cached config-0.5.1-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting flask_api==3.1 (from -r app/requirements.txt (line 10))
  Using cached Flask_API-3.1-py3-none-any.whl.metadata (940 bytes)
Collecting cbor_diag==1.0.1 (from -r app/requirements.txt (line 11))
  Downloading cbor_diag-1.0.1-cp39-none-win_amd64.whl.metadata (2.9 kB)
Collecting validators==0.22.0 (from -r app/requirements.txt (line 12))
  Using cached validators-0.22.0-py3-none-any.whl.metadata (4.7 kB)
Collecting Flask-Session==0.6.0 (from -r app/requirements.txt (line 13))
  Using cached flask_session-0.6.0-py3-none-any.whl.metadata (2.7 kB)
Collecting jsonschema==4.21.1 (from -r app/requirements.txt (line 14))
  Using cached jsonschema-4.21.1-py3-none-any.whl.metadata (7.8 kB)
Collecting werkzeug==2.3.7 (from -r app/requirements.txt (line 16))
  Using cached werkzeug-2.3.7-py3-none-any.whl.metadata (4.1 kB)
Collecting pycose==1.0.1 (from -r app/requirements.txt (line 17))
  Using cached pycose-1.0.1-py3-none-any.whl.metadata (6.5 kB)
Collecting cwt==2.3.2 (from -r app/requirements.txt (line 18))
  Using cached cwt-2.3.2-py3-none-any.whl.metadata (53 kB)
Collecting pyjwt==2.8.0 (from -r app/requirements.txt (line 19))
  Using cached PyJWT-2.8.0-py3-none-any.whl.metadata (4.2 kB)
Collecting schedule==1.2.1 (from -r app/requirements.txt (line 20))
  Using cached schedule-1.2.1-py2.py3-none-any.whl.metadata (3.3 kB)
Collecting pillow==10.2.0 (from -r app/requirements.txt (line 21))
  Downloading pillow-10.2.0-cp39-cp39-win_amd64.whl.metadata (9.9 kB)
Collecting segno==1.6.1 (from -r app/requirements.txt (line 22))
  Using cached segno-1.6.1-py3-none-any.whl.metadata (7.9 kB)
Collecting qrcode-artistic==3.0.2 (from -r app/requirements.txt (line 23))
  Using cached qrcode_artistic-3.0.2-py3-none-any.whl.metadata (4.3 kB)
Collecting gunicorn (from -r app/requirements.txt (line 24))
  Using cached gunicorn-23.0.0-py3-none-any.whl.metadata (4.4 kB)
Collecting charset-normalizer<4,>=2 (from requests==2.31.0->-r app/requirements.txt (line 2))
  Downloading charset_normalizer-3.3.2-cp39-cp39-win_amd64.whl.metadata (34 kB)
Collecting idna<4,>=2.5 (from requests==2.31.0->-r app/requirements.txt (line 2))
  Using cached idna-3.8-py3-none-any.whl.metadata (9.9 kB)
Collecting urllib3<3,>=1.21.1 (from requests==2.31.0->-r app/requirements.txt (line 2))
  Using cached urllib3-2.2.2-py3-none-any.whl.metadata (6.4 kB)
Collecting certifi>=2017.4.17 (from requests==2.31.0->-r app/requirements.txt (line 2))
  Using cached certifi-2024.8.30-py3-none-any.whl.metadata (2.2 kB)
Collecting Jinja2>=3.1.2 (from flask==2.3.3->-r app/requirements.txt (line 5))
  Using cached jinja2-3.1.4-py3-none-any.whl.metadata (2.6 kB)
Collecting itsdangerous>=2.1.2 (from flask==2.3.3->-r app/requirements.txt (line 5))
  Using cached itsdangerous-2.2.0-py3-none-any.whl.metadata (1.9 kB)
Collecting click>=8.1.3 (from flask==2.3.3->-r app/requirements.txt (line 5))
  Using cached click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Collecting blinker>=1.6.2 (from flask==2.3.3->-r app/requirements.txt (line 5))
  Using cached blinker-1.8.2-py3-none-any.whl.metadata (1.6 kB)
Collecting importlib-metadata>=3.6.0 (from flask==2.3.3->-r app/requirements.txt (line 5))
  Downloading importlib_metadata-8.4.0-py3-none-any.whl.metadata (4.7 kB)
Collecting attrs>=20.3.0 (from pyignite==0.6.1->-r app/requirements.txt (line 6))
  Using cached attrs-24.2.0-py3-none-any.whl.metadata (11 kB)
Collecting cachelib (from Flask-Session==0.6.0->-r app/requirements.txt (line 13))
  Using cached cachelib-0.13.0-py3-none-any.whl.metadata (2.0 kB)
Collecting jsonschema-specifications>=2023.03.6 (from jsonschema==4.21.1->-r app/requirements.txt (line 14))
  Using cached jsonschema_specifications-2023.12.1-py3-none-any.whl.metadata (3.0 kB)
Collecting referencing>=0.28.4 (from jsonschema==4.21.1->-r app/requirements.txt (line 14))
  Using cached referencing-0.35.1-py3-none-any.whl.metadata (2.8 kB)
Collecting rpds-py>=0.7.1 (from jsonschema==4.21.1->-r app/requirements.txt (line 14))
  Downloading rpds_py-0.20.0-cp39-none-win_amd64.whl.metadata (4.2 kB)
Collecting MarkupSafe>=2.1.1 (from werkzeug==2.3.7->-r app/requirements.txt (line 16))
  Downloading MarkupSafe-2.1.5-cp39-cp39-win_amd64.whl.metadata (3.1 kB)
Collecting cryptography (from pycose==1.0.1->-r app/requirements.txt (line 17))
  Using cached cryptography-43.0.0-cp39-abi3-win_amd64.whl.metadata (5.4 kB)
Collecting ecdsa (from pycose==1.0.1->-r app/requirements.txt (line 17))
  Using cached ecdsa-0.19.0-py2.py3-none-any.whl.metadata (29 kB)
Collecting certvalidator (from pycose==1.0.1->-r app/requirements.txt (line 17))
  Using cached certvalidator-0.11.1-py2.py3-none-any.whl.metadata (992 bytes)
Collecting asn1crypto<2.0.0,>=1.4.0 (from cwt==2.3.2->-r app/requirements.txt (line 18))
  Using cached asn1crypto-1.5.1-py2.py3-none-any.whl.metadata (13 kB)
Collecting cryptography (from pycose==1.0.1->-r app/requirements.txt (line 17))
  Using cached cryptography-41.0.7-cp37-abi3-win_amd64.whl.metadata (5.3 kB)
Collecting pyhpke<1.0.0,>=0.4.2 (from cwt==2.3.2->-r app/requirements.txt (line 18))
  Using cached pyhpke-0.5.4-py3-none-any.whl.metadata (5.6 kB)
Collecting packaging (from gunicorn->-r app/requirements.txt (line 24))
  Using cached packaging-24.1-py3-none-any.whl.metadata (3.2 kB)
Collecting pycose@ git+https://github.com/devisefutures/pycose.git@hsm (from pymdoccbor==0.5.4->-r app/requirements.txt (line 25))
  Cloning https://github.com/devisefutures/pycose.git (to revision hsm) to c:\users\paul\appdata\local\temp\pip-install-753itp5v\pycose_3477cdba5a424745a160a5323ec42abf
  Running command git clone --filter=blob:none --quiet https://github.com/devisefutures/pycose.git 'C:\Users\Paul\AppData\Local\Temp\pip-install-753itp5v\pycose_3477cdba5a424745a160a5323ec42abf'
  Running command git checkout -b hsm --track origin/hsm
  starting fsmonitor-daemon in 'C:/Users/Paul/AppData/Local/Temp/pip-install-753itp5v/pycose_3477cdba5a424745a160a5323ec42abf'
  Branch 'hsm' set up to track remote branch 'hsm' from 'origin'.
  Switched to a new branch 'hsm'
  Resolved https://github.com/devisefutures/pycose.git to commit 59f13117ea841377ed2d73ae630c10bf7aeecbad
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting python-pkcs11 (from pycose@ git+https://github.com/devisefutures/pycose.git@hsm->pymdoccbor==0.5.4->-r app/requirements.txt (line 25))
  Using cached python-pkcs11-0.7.0.tar.gz (106 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting cryptojwt>=1.8.4 (from idpyoidc==4.3.0->-r app/requirements.txt (line 26))
  Using cached cryptojwt-1.9.2-py3-none-any.whl.metadata (1.4 kB)
Collecting pyOpenSSL (from idpyoidc==4.3.0->-r app/requirements.txt (line 26))
  Using cached pyOpenSSL-24.2.1-py3-none-any.whl.metadata (13 kB)
Collecting filelock>=3.0.12 (from idpyoidc==4.3.0->-r app/requirements.txt (line 26))
  Using cached filelock-3.15.4-py3-none-any.whl.metadata (2.9 kB)
Collecting pyyaml>=5.1.2 (from idpyoidc==4.3.0->-r app/requirements.txt (line 26))
  Downloading PyYAML-6.0.2-cp39-cp39-win_amd64.whl.metadata (2.1 kB)
Collecting responses>=0.13.0 (from idpyoidc==4.3.0->-r app/requirements.txt (line 26))
  Using cached responses-0.25.3-py3-none-any.whl.metadata (46 kB)
Collecting jwcrypto>=1.3.1 (from sd-jwt==0.10.4->-r app/requirements.txt (line 28))
  Using cached jwcrypto-1.5.6-py3-none-any.whl.metadata (3.1 kB)
Collecting oscrypto>=0.16.1 (from certvalidator->pycose==1.0.1->-r app/requirements.txt (line 17))
  Using cached oscrypto-1.3.0-py2.py3-none-any.whl.metadata (15 kB)
Collecting colorama (from click>=8.1.3->flask==2.3.3->-r app/requirements.txt (line 5))
  Using cached colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Collecting cffi>=1.12 (from cryptography->pycose==1.0.1->-r app/requirements.txt (line 17))
  Downloading cffi-1.17.0-cp39-cp39-win_amd64.whl.metadata (1.6 kB)
Collecting zipp>=0.5 (from importlib-metadata>=3.6.0->flask==2.3.3->-r app/requirements.txt (line 5))
  Downloading zipp-3.20.1-py3-none-any.whl.metadata (3.7 kB)
Collecting typing-extensions>=4.5.0 (from jwcrypto>=1.3.1->sd-jwt==0.10.4->-r app/requirements.txt (line 28))
  Using cached typing_extensions-4.12.2-py3-none-any.whl.metadata (3.0 kB)
INFO: pip is looking at multiple versions of pyhpke to determine which version is compatible with other requirements. This could take a while.
Collecting pyhpke<1.0.0,>=0.4.2 (from cwt==2.3.2->-r app/requirements.txt (line 18))
  Using cached pyhpke-0.5.3-py3-none-any.whl.metadata (5.6 kB)
  Using cached pyhpke-0.5.2-py3-none-any.whl.metadata (5.6 kB)
Collecting six>=1.9.0 (from ecdsa->pycose==1.0.1->-r app/requirements.txt (line 17))
  Using cached six-1.16.0-py2.py3-none-any.whl.metadata (1.8 kB)
Collecting cached-property (from python-pkcs11->pycose@ git+https://github.com/devisefutures/pycose.git@hsm->pymdoccbor==0.5.4->-r app/requirements.txt (line 25))
  Using cached cached_property-1.5.2-py2.py3-none-any.whl.metadata (11 kB)
Collecting pycparser (from cffi>=1.12->cryptography->pycose==1.0.1->-r app/requirements.txt (line 17))
  Using cached pycparser-2.22-py3-none-any.whl.metadata (943 bytes)
Using cached Flask_Cors-4.0.0-py2.py3-none-any.whl (14 kB)
Using cached requests-2.31.0-py3-none-any.whl (62 kB)
Downloading cbor2-5.4.6-cp39-cp39-win_amd64.whl (59 kB)
Using cached pytz-2023.4-py2.py3-none-any.whl (506 kB)
Using cached flask-2.3.3-py3-none-any.whl (96 kB)
Downloading pyignite-0.6.1-cp39-cp39-win_amd64.whl (138 kB)
Using cached pycryptodome-3.20.0-cp35-abi3-win_amd64.whl (1.8 MB)
Using cached config-0.5.1-py2.py3-none-any.whl (20 kB)
Using cached Flask_API-3.1-py3-none-any.whl (138 kB)
Downloading cbor_diag-1.0.1-cp39-none-win_amd64.whl (219 kB)
Using cached validators-0.22.0-py3-none-any.whl (26 kB)
Using cached flask_session-0.6.0-py3-none-any.whl (8.6 kB)
Using cached jsonschema-4.21.1-py3-none-any.whl (85 kB)
Using cached werkzeug-2.3.7-py3-none-any.whl (242 kB)
Using cached cwt-2.3.2-py3-none-any.whl (98 kB)
Using cached PyJWT-2.8.0-py3-none-any.whl (22 kB)
Using cached schedule-1.2.1-py2.py3-none-any.whl (11 kB)
Downloading pillow-10.2.0-cp39-cp39-win_amd64.whl (2.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.6/2.6 MB 30.2 MB/s eta 0:00:00
Using cached segno-1.6.1-py3-none-any.whl (73 kB)
Using cached qrcode_artistic-3.0.2-py3-none-any.whl (7.6 kB)
Using cached gunicorn-23.0.0-py3-none-any.whl (85 kB)
Using cached asn1crypto-1.5.1-py2.py3-none-any.whl (105 kB)
Using cached attrs-24.2.0-py3-none-any.whl (63 kB)
Using cached blinker-1.8.2-py3-none-any.whl (9.5 kB)
Using cached certifi-2024.8.30-py3-none-any.whl (167 kB)
Using cached certvalidator-0.11.1-py2.py3-none-any.whl (31 kB)
Downloading charset_normalizer-3.3.2-cp39-cp39-win_amd64.whl (100 kB)
Using cached click-8.1.7-py3-none-any.whl (97 kB)
Using cached cryptography-41.0.7-cp37-abi3-win_amd64.whl (2.7 MB)
Using cached cryptojwt-1.9.2-py3-none-any.whl (90 kB)
Using cached filelock-3.15.4-py3-none-any.whl (16 kB)
Using cached idna-3.8-py3-none-any.whl (66 kB)
Downloading importlib_metadata-8.4.0-py3-none-any.whl (26 kB)
Using cached itsdangerous-2.2.0-py3-none-any.whl (16 kB)
Using cached jinja2-3.1.4-py3-none-any.whl (133 kB)
Using cached jsonschema_specifications-2023.12.1-py3-none-any.whl (18 kB)
Using cached jwcrypto-1.5.6-py3-none-any.whl (92 kB)
Downloading MarkupSafe-2.1.5-cp39-cp39-win_amd64.whl (17 kB)
Using cached pyhpke-0.5.2-py3-none-any.whl (50 kB)
Downloading PyYAML-6.0.2-cp39-cp39-win_amd64.whl (162 kB)
Using cached referencing-0.35.1-py3-none-any.whl (26 kB)
Using cached responses-0.25.3-py3-none-any.whl (55 kB)
Downloading rpds_py-0.20.0-cp39-none-win_amd64.whl (213 kB)
Using cached urllib3-2.2.2-py3-none-any.whl (121 kB)
Using cached ecdsa-0.19.0-py2.py3-none-any.whl (149 kB)
Using cached packaging-24.1-py3-none-any.whl (53 kB)
Using cached pyOpenSSL-24.2.1-py3-none-any.whl (58 kB)
Downloading cffi-1.17.0-cp39-cp39-win_amd64.whl (180 kB)
Using cached oscrypto-1.3.0-py2.py3-none-any.whl (194 kB)
Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Using cached typing_extensions-4.12.2-py3-none-any.whl (37 kB)
Downloading zipp-3.20.1-py3-none-any.whl (9.0 kB)
Using cached cached_property-1.5.2-py2.py3-none-any.whl (7.6 kB)
Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Using cached pycparser-2.22-py3-none-any.whl (117 kB)
Building wheels for collected packages: tinyec, pymdoccbor, pycose, idpyoidc, openid4v, sd-jwt, fedservice, idpysdjwt, python-pkcs11
  Created wheel for tinyec: filename=tinyec-0.4.0-py3-none-any.whl size=20896 sha256=acb85edece1445101ff21758a1cf2fa496fed96c3023d7391537811c8e6a7054
  Stored in directory: c:\users\paul\appdata\local\pip\cache\wheels\40\b9\44\1115d191053b74c238a0c2c1c09f66d0e21186489af0fa33f4
  Building wheel for pymdoccbor (pyproject.toml) ... done
  Created wheel for pymdoccbor: filename=pymdoccbor-0.5.4-py3-none-any.whl size=14285 sha256=8de1dc9ef5dc19a60dc66706446b984703882c8efe41871b0318f83f785ac820
  Stored in directory: C:\Users\Paul\AppData\Local\Temp\pip-ephem-wheel-cache-rui8lnkx\wheels\63\0f\20\6259de413a84f320b6ab3a827734d65eac1887a61a2b48a9b4
  Building wheel for pycose (pyproject.toml) ... done
  Created wheel for pycose: filename=pycose-1.0.1-py3-none-any.whl size=12223 sha256=f6b402f7e5be1a31ac164af127204ba1a081875edf81cd6f55bc185457a82f42
  Stored in directory: C:\Users\Paul\AppData\Local\Temp\pip-ephem-wheel-cache-rui8lnkx\wheels\8c\6d\90\2dd93d9083ecb4355646d66857414b980e14279cf681bcece5
  Building wheel for idpyoidc (pyproject.toml) ... done
  Created wheel for idpyoidc: filename=idpyoidc-4.3.0-py3-none-any.whl size=284151 sha256=9c38fdabce8c920017df42671d89433f9aafd9a3bd84b1ab4912e830dfa06c2f
  Stored in directory: C:\Users\Paul\AppData\Local\Temp\pip-ephem-wheel-cache-rui8lnkx\wheels\a4\2f\a5\cb3a38c9f17d9bd4d4422fb4ef2f613c286878d87c60d2da6a
  Building wheel for openid4v (pyproject.toml) ... done
  Created wheel for openid4v: filename=openid4v-0.1.0-py3-none-any.whl size=41894 sha256=868a6be0ca56fb8eaeedce402c3f0ad079c7ccd5c4eb31bdb83914ec1ec57b19
  Stored in directory: C:\Users\Paul\AppData\Local\Temp\pip-ephem-wheel-cache-rui8lnkx\wheels\b0\84\b2\87c69513dbc1ef9d69f2fd5dc22dcc8da7a307ab77db78913f
  Building wheel for sd-jwt (pyproject.toml) ... done
  Created wheel for sd-jwt: filename=sd_jwt-0.10.4-py3-none-any.whl size=27718 sha256=d8d9999347c9dee9895440cbae4d60e92c6ec4f70208493fe4e08c18651dd532
  Stored in directory: c:\users\paul\appdata\local\pip\cache\wheels\8b\f0\cb\b97ed10a3fd4d9a2ed4391ef1fa50b7cca6e09e0f9274a459d
  Building wheel for fedservice (pyproject.toml) ... done
  Created wheel for fedservice: filename=fedservice-5.0.0-py3-none-any.whl size=104299 sha256=22da3cfe1644d6086dffc8ef824ead09983358634651c2838d956f14aa3238f4
  Stored in directory: C:\Users\Paul\AppData\Local\Temp\pip-ephem-wheel-cache-rui8lnkx\wheels\4c\91\bf\5735d8d5d8de6c6a9527217732e1deebcf627d0a3f843abdb6
  Building wheel for idpysdjwt (pyproject.toml) ... done
  Created wheel for idpysdjwt: filename=idpysdjwt-0.0.1-py3-none-any.whl size=12414 sha256=273609b3798e62dde7393fd323c58b531ec297672cf571d94a3c3a07d001291e
  Stored in directory: C:\Users\Paul\AppData\Local\Temp\pip-ephem-wheel-cache-rui8lnkx\wheels\11\59\93\e60c9624ca87eba0ecadde30519303ccb376478f147b258649
  Building wheel for python-pkcs11 (pyproject.toml) ... done
  Created wheel for python-pkcs11: filename=python_pkcs11-0.7.0-cp39-cp39-win_amd64.whl size=269147 sha256=d3395497f2d6cd355d223716f4456cc3f9eedc3589bf597fa63348bc91c997f5
  Stored in directory: c:\users\paul\appdata\local\pip\cache\wheels\8f\9b\83\03a9f544ae723155c0d89a606e57e7ad4ac8974723fd6156ff
Successfully built tinyec pymdoccbor pycose idpyoidc openid4v sd-jwt fedservice idpysdjwt python-pkcs11
Installing collected packages: tinyec, pytz, config, cached-property, asn1crypto, zipp, validators, urllib3, typing-extensions, six, schedule, rpds-py, pyyaml, python-pkcs11, pyjwt, pycryptodome, pycparser, pillow, packaging, oscrypto, MarkupSafe, itsdangerous, idna, filelock, colorama, charset-normalizer, certifi, cbor2, cbor_diag, cachelib, blinker, attrs, werkzeug, requests, referencing, pyignite, Jinja2, importlib-metadata, gunicorn, ecdsa, click, cffi, certvalidator, segno, responses, jsonschema-specifications, flask, cryptography, qrcode-artistic, pyOpenSSL, pyhpke, pycose, jwcrypto, jsonschema, idpysdjwt, Flask-Session, Flask-Cors, flask_api, cryptojwt, sd-jwt, idpyoidc, cwt, pymdoccbor, openid4v, fedservice
Successfully installed Flask-Cors-4.0.0 Flask-Session-0.6.0 Jinja2-3.1.4 MarkupSafe-2.1.5 asn1crypto-1.5.1 attrs-24.2.0 blinker-1.8.2 cached-property-1.5.2 cachelib-0.13.0 cbor2-5.4.6 cbor_diag-1.0.1 certifi-2024.8.30 certvalidator-0.11.1 cffi-1.17.0 charset-normalizer-3.3.2 click-8.1.7 colorama-0.4.6 config-0.5.1 cryptography-41.0.7 cryptojwt-1.9.2 cwt-2.3.2 ecdsa-0.19.0 fedservice-5.0.0 filelock-3.15.4 flask-2.3.3 flask_api-3.1 gunicorn-23.0.0 idna-3.8 idpyoidc-4.3.0 idpysdjwt-0.0.1 importlib-metadata-8.4.0 itsdangerous-2.2.0 jsonschema-4.21.1 jsonschema-specifications-2023.12.1 jwcrypto-1.5.6 openid4v-0.1.0 oscrypto-1.3.0 packaging-24.1 pillow-10.2.0 pyOpenSSL-24.2.1 pycose-1.0.1 pycparser-2.22 pycryptodome-3.20.0 pyhpke-0.5.2 pyignite-0.6.1 pyjwt-2.8.0 pymdoccbor-0.5.4 python-pkcs11-0.7.0 pytz-2023.4 pyyaml-6.0.2 qrcode-artistic-3.0.2 referencing-0.35.1 requests-2.31.0 responses-0.25.3 rpds-py-0.20.0 schedule-1.2.1 sd-jwt-0.10.4 segno-1.6.1 six-1.16.0 tinyec-0.4.0 typing-extensions-4.12.2 urllib3-2.2.2 validators-0.22.0 werkzeug-2.3.7 zipp-3.20.1
```

</details>

<details><summary>Installed Packages</summary>

```
(.venv) PS C:\Workspace\cm\EUDI-Wallet\eudi-srv-web-issuing-eudiw-py> pip list
Package                   Version
------------------------- ---------
asn1crypto                1.5.1
attrs                     24.2.0
blinker                   1.8.2
cached-property           1.5.2
cachelib                  0.13.0
cbor-diag                 1.0.1
cbor2                     5.4.6
certifi                   2024.8.30
certvalidator             0.11.1
cffi                      1.17.0
charset-normalizer        3.3.2
click                     8.1.7
colorama                  0.4.6
config                    0.5.1
cryptography              41.0.7
cryptojwt                 1.9.2
cwt                       2.3.2
ecdsa                     0.19.0
fedservice                5.0.0
filelock                  3.15.4
Flask                     2.3.3
Flask-API                 3.1
Flask-Cors                4.0.0
Flask-Session             0.6.0
gunicorn                  23.0.0
idna                      3.8
idpyoidc                  4.3.0
idpysdjwt                 0.0.1
importlib_metadata        8.4.0
itsdangerous              2.2.0
Jinja2                    3.1.4
jsonschema                4.21.1
jsonschema-specifications 2023.12.1
jwcrypto                  1.5.6
MarkupSafe                2.1.5
openid4v                  0.1.0
oscrypto                  1.3.0
packaging                 24.1
pillow                    10.2.0
pip                       24.2
pycose                    1.0.1
pycparser                 2.22
pycryptodome              3.20.0
pyhpke                    0.5.2
pyignite                  0.6.1
PyJWT                     2.8.0
pymdoccbor                0.5.4
pyOpenSSL                 24.2.1
python-pkcs11             0.7.0
pytz                      2023.4
PyYAML                    6.0.2
qrcode-artistic           3.0.2
referencing               0.35.1
requests                  2.31.0
responses                 0.25.3
rpds-py                   0.20.0
schedule                  1.2.1
sd-jwt                    0.10.4
segno                     1.6.1
setuptools                49.2.1
six                       1.16.0
tinyec                    0.4.0
typing_extensions         4.12.2
urllib3                   2.2.2
validators                0.22.0
Werkzeug                  2.3.7
zipp                      3.20.1
```

</details>

**Edit:** I tested the setup on WSL and I did not face the issue.

**Comment by AlessandroFerrara00** [comment]
Hi, I had the same problem. You did everything right, unfortunately the problem is Windows not downloading certain package extensions. I solved it this way:

[folder.zip](https://github.com/user-attachments/files/16828932/folder.zip)
take the packages inside this ‘folder’ folder and put them in your project in the ‘pycose’ folder which should be in ‘eudi-srv-web-issuing-eudiw-py\.venv\Lib\site-packages’.

[doccbor.zip](https://github.com/user-attachments/files/16828934/doccbor.zip)
Do a similar thing with the packages inside the ‘doccbor’ folder and put them in the ‘pymdoccbor’ folder of your project, which is also in the same location as before.
I hope I have been of some help.
